/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as QuanRouteImport } from './routes/quan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MapRouteImport } from './routes/map'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as QuestChatQuestIdRouteImport } from './routes/quest-chat.$questId'
import { Route as MessagesUserIdRouteImport } from './routes/messages.$userId'

const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanRoute = QuanRouteImport.update({
  id: '/quan',
  path: '/quan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestChatQuestIdRoute = QuestChatQuestIdRouteImport.update({
  id: '/quest-chat/$questId',
  path: '/quest-chat/$questId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUserIdRoute = MessagesUserIdRouteImport.update({
  id: '/messages/$userId',
  path: '/messages/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/map': typeof MapRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/quan': typeof QuanRoute
  '/quests': typeof QuestsRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/quest-chat/$questId': typeof QuestChatQuestIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/map': typeof MapRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/quan': typeof QuanRoute
  '/quests': typeof QuestsRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/quest-chat/$questId': typeof QuestChatQuestIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/map': typeof MapRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/quan': typeof QuanRoute
  '/quests': typeof QuestsRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/quest-chat/$questId': typeof QuestChatQuestIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/feed'
    | '/how-it-works'
    | '/leaderboard'
    | '/map'
    | '/pricing'
    | '/profile'
    | '/quan'
    | '/quests'
    | '/messages/$userId'
    | '/quest-chat/$questId'
    | '/u/$userId'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/feed'
    | '/how-it-works'
    | '/leaderboard'
    | '/map'
    | '/pricing'
    | '/profile'
    | '/quan'
    | '/quests'
    | '/messages/$userId'
    | '/quest-chat/$questId'
    | '/u/$userId'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/feed'
    | '/how-it-works'
    | '/leaderboard'
    | '/map'
    | '/pricing'
    | '/profile'
    | '/quan'
    | '/quests'
    | '/messages/$userId'
    | '/quest-chat/$questId'
    | '/u/$userId'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  FeedRoute: typeof FeedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MapRoute: typeof MapRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  QuanRoute: typeof QuanRoute
  QuestsRoute: typeof QuestsRoute
  MessagesUserIdRoute: typeof MessagesUserIdRoute
  QuestChatQuestIdRoute: typeof QuestChatQuestIdRoute
  UUserIdRoute: typeof UUserIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan': {
      id: '/quan'
      path: '/quan'
      fullPath: '/quan'
      preLoaderRoute: typeof QuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest-chat/$questId': {
      id: '/quest-chat/$questId'
      path: '/quest-chat/$questId'
      fullPath: '/quest-chat/$questId'
      preLoaderRoute: typeof QuestChatQuestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$userId': {
      id: '/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof MessagesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  FeedRoute: FeedRoute,
  HowItWorksRoute: HowItWorksRoute,
  LeaderboardRoute: LeaderboardRoute,
  MapRoute: MapRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  QuanRoute: QuanRoute,
  QuestsRoute: QuestsRoute,
  MessagesUserIdRoute: MessagesUserIdRoute,
  QuestChatQuestIdRoute: QuestChatQuestIdRoute,
  UUserIdRoute: UUserIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
