
-- 1) Make chat-media bucket private
UPDATE storage.buckets SET public = false WHERE id = 'chat-media';

-- 2) Drop overly broad read policies on chat-media
DROP POLICY IF EXISTS "Public read chat media" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated read chat media" ON storage.objects;

-- 3) Allow only the uploader (path's first folder = auth.uid()) to read.
--    Recipients/participants view media through signed URLs generated by the uploader.
CREATE POLICY "Uploader reads own chat media"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'chat-media'
  AND auth.uid()::text = (storage.foldername(name))[1]
);

-- 4) Realtime channel subscription RLS
ALTER TABLE realtime.messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "DM channel access" ON realtime.messages;
CREATE POLICY "DM channel access"
ON realtime.messages FOR SELECT
TO authenticated
USING (
  realtime.topic() LIKE 'chat:%'
  AND (
    split_part(realtime.topic(), ':', 2) = auth.uid()::text
    OR split_part(realtime.topic(), ':', 3) = auth.uid()::text
  )
);

DROP POLICY IF EXISTS "Quest chat channel access" ON realtime.messages;
CREATE POLICY "Quest chat channel access"
ON realtime.messages FOR SELECT
TO authenticated
USING (
  realtime.topic() LIKE 'quest-chat:%'
  AND public.is_quest_participant(
    NULLIF(split_part(realtime.topic(), ':', 2), '')::uuid,
    auth.uid()
  )
);
